// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (id, first_name, last_name, email, address_1, address_2, postal_code)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, first_name, last_name, email, address_1, address_2, postal_code
`

type CreateCustomerParams struct {
	ID         uuid.UUID
	FirstName  string
	LastName   string
	Email      string
	Address1   sql.NullString
	Address2   sql.NullString
	PostalCode string
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Address1,
		arg.Address2,
		arg.PostalCode,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Address1,
		&i.Address2,
		&i.PostalCode,
	)
	return i, err
}

const getCustomerByFirstName = `-- name: GetCustomerByFirstName :one
SELECT id, first_name, last_name, email, address_1, address_2, postal_code FROM customers
WHERE first_name = $1
`

func (q *Queries) GetCustomerByFirstName(ctx context.Context, firstName string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByFirstName, firstName)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Address1,
		&i.Address2,
		&i.PostalCode,
	)
	return i, err
}
