// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Customer struct {
	ID         interface{}
	FirstName  string
	LastName   string
	Email      string
	Address1   sql.NullString
	Address2   sql.NullString
	PostalCode string
}

type Order struct {
	ID         interface{}
	CustomerID interface{}
	RegionID   interface{}
	OrderDate  time.Time
	Status     string
}

type OrderItem struct {
	ID        interface{}
	OrderID   interface{}
	ProductID interface{}
	Quantity  int64
}

type Product struct {
	ID          interface{}
	ProductName string
	Price       float64
}

type Region struct {
	ID           interface{}
	RegionName   string
	ShippingRate float64
}
