// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Customer struct {
	ID         uuid.UUID
	FirstName  string
	LastName   string
	Email      string
	Address1   sql.NullString
	Address2   sql.NullString
	PostalCode string
}

type Order struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	RegionID   uuid.UUID
	OrderDate  time.Time
	Status     string
}

type OrderItem struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
}

type Product struct {
	ID          uuid.UUID
	ProductName string
	Price       string
}

type Region struct {
	ID           uuid.UUID
	RegionName   string
	ShippingRate string
}
